version: '3.8'

services:
  # api:
  #   image: byte-eats-api:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "12005:8080"
  #   # environment:
  #   #   - ASPNETCORE_ENVIRONMENT=Production
  #   #   - ConnectionStrings__DefaultConnection=Server=172.22.35.172,12000;Database=ByteEats;User Id=sa;Password=ByteEats1;TrustServerCertificate=True;
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ByteEats1
      ACCEPT_EULA: "Y"
    ports:
      - "12000:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data: